security:
    # ...
    providers:
       
        app_user_provider:
            entity:
                class: App\Entity\User
               

    firewalls:
        # ...
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider 
            custom_authenticator: App\Security\JwtAuthenticator